on: [push]
jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: saying hello job   
    steps:
      - name: checking out
        uses: actions/checkout@v2
      - name: hello world action
        uses: ./action.yaml
        id: hello
        with:
          who-to-greet: 'alex awesome'
      - name: print output
        run: echo "the time when ran was $({ steps.hello.outputs.time })"
